accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/', views.profile_view, name='profile'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('follow_recommend/', views.follow_recommend, name='follow_recommend'),
    path('follower_list/', views.follower_list, name='follower_list'),
    re_path(r'^(?P<username>[\w.@+-]+)/follows/$', views.user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollows/$', views.user_unfollow, name='user_unfollow'),

]

board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nboard/', include('nboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(pattern_name='accounts:profile'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG == True:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

nboard/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'nboard'



urlpatterns = [
    path('post_create/', views.post_create, name='post_create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<int:pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    path('<int:pk>/comment_edit/<int:comment_pk>/', views.comment_edit, name='comment_edit'),
    path('<int:pk>/post_update/', views.post_update, name='post_update'),
    path('<int:pk>/post_delete/', views.post_delete, name='post_delete'),
    path('<int:pk>/post_like/', views.post_like, name='post_like'),
    path('<int:pk>/post_unlike/', views.post_unlike, name='post_unlike'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from django_auto_one_to_one import AutoOneToOneModel


class User(AbstractUser):
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=128)
    following_set = models.ManyToManyField("self", blank=True)
    follower_set = models.ManyToManyField("self", blank=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField(max_length=254, blank=True)


def user_profile_path(instance, filename):
    return 'nboard/profile/user_{}/{}'.format(instance.user, filename)


class Profile(AutoOneToOneModel(User)):
    user_photo = models.ImageField(blank=True, upload_to=user_profile_path)
    status_message = models.CharField(blank=True, max_length=300)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms.models import ModelForm
from .models import Profile


class UserForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email']


class ProfileForm(ModelForm):

    class Meta:
        model = Profile
        fields = ['user_photo', 'status_message']

accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserForm, ProfileForm
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model, login
from .models import Profile, User
from nboard.models import Post


# 로그인 뷰
# redirect는 기본적으로 profile로 지정되어 있으므로 미지정
class LoginView(LoginView):
    model = get_user_model()
    template_name = 'accounts/login.html'


# 로그아웃 뷰
# 로그아웃시 login 페이지로 이동
class LogoutView(LogoutView):
    next_page = reverse_lazy('accounts:login')


login_view = LoginView.as_view()
logout_view = LogoutView.as_view()


# 회원가입 함수
def signup_view(request):
    # POST 일땐 login 시도
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:profile')
    else:
        form = UserForm
    # GET 일땐 회원가입 form 리턴
    return render(request, 'accounts/signup.html', {
        'form': form,
    })


# profile view
@login_required
def profile_view(request):
    profile = get_object_or_404(Profile, user_id=request.user.pk)
    # 팔로우 한 유저와 내가 쓴 post만 담음
    post_list = Post.objects.all() \
        .filter(
        Q(author__in=request.user.following_set.all()) |
        Q(author=request.user)
    )
    # 로그인 한 유저의 profile과 post_list 리턴
    return render(request, 'accounts/profile.html', {
        'profile': profile,
        'post_list': post_list,
    })


# profile update
@login_required
def profile_edit(request):
    if request.POST:
        # 함수방식에선 파일도 보낼 시 request.POST, request.FILES가 포함되어야함
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user
            profile.save()
        return redirect('accounts:profile')

    # update를 하기 위해 본인의 profile을 form의 instance로 담아 리턴해줌
    profile = Profile.objects.get(pk=request.user.pk)
    profile_form = ProfileForm(instance=profile)
    return render(request, 'accounts/profile_edit_form.html', {
        'form': profile_form,
    })


# follow 추천
@login_required
def follow_recommend(request):
    profile = get_object_or_404(Profile, user_id=request.user.pk)
    # 나와 팔로우 한 user를 제외한 나머지를 suggested_user_list로 담음
    suggested_user_list = get_user_model().objects.all() \
        .exclude(pk=request.user.pk) \
        .exclude(pk__in=request.user.following_set.all())

    return render(request, 'accounts/profile.html', {
        'profile': profile,
        'suggested_user_list': suggested_user_list
    })


# 팔로우 되어있는 user 리스트
@login_required
def follower_list(request):
    profile = get_object_or_404(Profile, user_id=request.user.pk)
    # 나와 내가 팔로한 유저만 filter 하려 follower_list에 저장
    follower_list = get_user_model().objects.all() \
        .exclude(pk=request.user.pk) \
        .filter(pk__in=request.user.following_set.all())

    return render(request, 'accounts/profile.html', {
        'profile': profile,
        'follower_list': follower_list
    })


# user follow 기능
@login_required
def user_follow(request, username):
    follow_user = get_object_or_404(User, username=username, is_active=True)
    request.user.following_set.add(follow_user)
    follow_user.follower_set.add(request.user)
    messages.success(request, f"{follow_user}님을 팔로우 했습니다.")
    # 요청한 주소로 다시 redirect
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)


# user unfollow 기능
@login_required
def user_unfollow(request, username):
    unfollow_user = get_object_or_404(User, username=username, is_active=True)
    request.user.following_set.remove(unfollow_user)
    unfollow_user.follower_set.remove(request.user)
    messages.success(request, f"{unfollow_user}님을 언팔로우 했습니다.")
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)

accounts/templates/accounts/follow_recommend.html
{% block content %}
{% if suggested_user_list %}
<div class="container">
    <ul class="list-group">
        {% for suggested in suggested_user_list %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{suggested}}
            <a class="btn btn-primary" href="{% url 'accounts:user_follow' suggested %}">팔로우</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}
{% endblock %}

accounts/templates/accounts/follower_list.html
{% block content %}
{% if follower_list %}
<div class="container">
    <ul class="list-group">
        {% for follower in follower_list %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{follower}}
            <a class="btn btn-primary" href="{% url 'accounts:user_unfollow' follower %}">언팔로우</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endif %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
{% include "form.html" with submit_label="로그인" %}
{% buttons %}

{% endbuttons %}
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %} {% block profile %}
<div class="container">
  <div class="container">
    <div class="row text-center">
      {% if profile %} {% if profile.user_photo %}
      <img
        src="{{ profile.user_photo.url }}"
        alt="{{ profile.user }}"
        class="rounded mx-auto d-block"
        style="width: 25%; align-content: center"
      />
      {% else %}
      <svg
        class="bd-placeholder-img card-img-top"
        width="100%"
        height="225"
        xmlns="http://www.w3.org/2000/svg"
        role="img"
        aria-label="Placeholder: Thumbnail"
        preserveAspectRatio="xMidYMid slice"
        focusable="false"
      >
        <title>Placeholder</title>
        <rect width="100%" height="100%" fill="#55595c"></rect>
        <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#eceeef" dy=".3em">이미지 없음</text>
      </svg>
      {% endif %}
      <div class="container">{{ profile.user }}</div>
      <div class="container">
        상태메세지
        <div>{{ profile.status_message }}</div>
      </div>
      {% endif %}
      <div class="container mb-3">
        <a href="{% url 'nboard:post_create' %}" class="btn btn-primary"
          >새 글 쓰기</a
        >
        <a class="btn btn-primary" href="{% url 'accounts:profile_edit' %}"
          >프로필 편집</a
        >
      </div>
      <hr />
    </div>

    <div>
      <div class="container">
        <ul class="nav justify-content-center">
          <li class="nav-item">
            <a
              class="nav-link active"
              aria-current="page"
              href="{% url 'accounts:profile' %}"
              >게시물</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:follow_recommend' %}"
              >팔로워 추천</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:follower_list' %}"
              >팔로잉 리스트</a
            >
          </li>
        </ul>
      </div>
    </div>
  </div>
  <hr />
</div>
{% endblock %} {% block content %}
<div class="row row-cols-3 row-cols-sm-2 row-cols-md-4 g-3">
  {% include "nboard/post_list.html" %}
</div>
<div class="container mt-5">{% include "accounts/follow_recommend.html" %}</div>
<div class="container mt-5">{% include "accounts/follower_list.html" %}</div>
{% endblock %}

accounts/templates/accounts/profile_edit_form.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
    {% include "form.html" with submit_label="프로필 저장" %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
{% include "form.html" with submit_label="회원가입" %}
{% buttons %}
{% endbuttons %}
{% endblock %}