board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nboard/', include('nboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(pattern_name='accounts:profile'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG == True:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

nboard/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'nboard'



urlpatterns = [
    path('post_create/', views.post_create, name='post_create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<int:pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    path('<int:pk>/comment_edit/<int:comment_pk>/', views.comment_edit, name='comment_edit'),
    path('<int:pk>/post_update/', views.post_update, name='post_update'),
    path('<int:pk>/post_delete/', views.post_delete, name='post_delete'),
    path('<int:pk>/post_like/', views.post_like, name='post_like'),
    path('<int:pk>/post_unlike/', views.post_unlike, name='post_unlike'),
]

nboard/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
import re


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(max_length=300)
    photo = models.ImageField(upload_to="nboard/post/%Y/%m/%d", blank=True)
    tag = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_post_set", blank=True)

    class Meta:
        ordering = ['-id']

    def get_absolute_url(self):
        return reverse('nboard:post_detail', args=[self.pk])

    def is_like_user(self, user):
        return self.like_user.filter(pk=user.pk).exists()

    def extract_tag_list(self):
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.message)
        tag_list = []
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        return tag_list


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()

    class Meta:
        ordering = ['-id']


class Tag(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

nboard/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', 'photo']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

nboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, UpdateView, CreateView, DetailView, DeleteView
from django.contrib import messages
from .models import Post, Comment
from .forms import PostForm, CommentForm


# 사용하지 않는 코드
# profile에서 postlist가 쓰임
class PostListView(ListView):
    def get(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            qs = Post.objects.all() \
                .filter(
                Q(author__in=request.user.following_set.all()) |
                Q(author=request.user)
            )
            if qs:
                paginator, page, queryset, is_paginated = super().paginate_queryset(qs, 9)
                context = {
                    'paginator': paginator,
                    'page': page,
                    'is_paginated': is_paginated,
                    'post_list': queryset,
                }
                return render(request, 'nboard/post_list.html', context)
        return render(request, 'nboard/post_list.html', {
            'post_list': None
        })


# post 생성뷰
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    # post로 받은 form이 유효하다면
    def form_valid(self, form):
        new_form = form.save(commit=False)
        new_form.author = self.request.user # form에 넣지 않은 author를 request.user로 지정
        new_form.save()
        new_form.tag.add(*new_form.extract_tag_list()) # 해쉬태그 형식으로 적은 내용들 tag에 add
        messages.success(self.request, '포스팅 저장 완료')
        return super().form_valid(form)


# post update view
class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm

    # update 요청시
    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(Post, pk=kwargs['pk'])
        # 작성한 회원이 아니라면
        if self.object.author != request.user:
            messages.warning(self.request, '작성한 회원만 수정할 수 있습니다')
            # 기존 detailview로 이동
            return redirect(self.object)
        form = PostForm
        return super(PostUpdateView, self).get(form)

    # update한 form이 유효하다면
    def form_valid(self, form):
        self.object = form.save(commit=False)
        # 요청한 회원이 post의 작성자와 같다면
        if self.object.author == self.request.user:
            messages.success(self.request, '포스팅 수정 완료')
            form.save()
            # 해쉬태그로 적힌 tag들 set하여 재 지정
            self.object.tag.set(self.object.extract_tag_list())
        # 아니라면 return
        else:
            messages.warning(self.request, '작성한 회원만 수정할 수 있습니다')
        return super().form_valid(form)


# post delect view
class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name_suffix = '_delete'        # _delete가 들어간 html file을 template으로 지정
    success_url = 'nboard/post_list.html'
    
    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(Post, pk=kwargs['pk'])
        # 작성한 회원이 아니라면 return detail view
        if self.object.author != request.user:
            messages.warning(self.request, '작성한 회원만 삭제할수 있습니다')
            return redirect(self.object)
        return super(PostDeleteView, self).get(Post)

    def post(self, request, *args, **kwargs):
        self.object = get_object_or_404(Post, pk=kwargs['pk'])
        # 작성한 회원이 아니라면 return detail view
        if self.object.author != request.user:
            messages.warning(self.request, '작성한 회원만 삭제할수 있습니다')
            return redirect(self.object)
        # 맞다면 post delete
        self.object.delete()
        messages.success(request, '포스팅 삭제 완료')
        # profile로 이동
        return redirect('accounts:profile')


# post detail view
class PostDetailView(DetailView):
    model = Post

    # post와 comment를 같이 넣기 위해서 comment conetext 추가
    def get_context_data(self, **kwargs):
        comment_list = Comment.objects.filter(post=kwargs.get('object'))
        comment_form = CommentForm()
        context = {
            'comment_list': comment_list,
            'form': comment_form
        }
        return super().get_context_data(**context)

    # comment 저장 post
    def post(self, request, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = super().get_object()
            comment.save()
            return redirect('nboard:post_detail', pk=kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        pk = request.GET.get('pk', '')  # comment 수정에 쓰일 comment.pk
        # comment pk값이 넘어왔다면
        if pk:
            comment = Comment.objects.get(pk=pk)
            if comment.author != request.user:
                messages.warning(request, message="작성자가 아닙니다")
                return
            # 기존 object를 가져와서 저장
            self.object = self.get_object()
            # comment update에 쓰일 comment initial dict 미리 생성
            # 사실 author와 post는 필요없음
            # 왜냐하면 form엔 comment만 쓰이기 때문에...
            initial_dict = {
                "comment": comment.comment,
                "author": comment.author,
                "post": comment.post,
            }
            # 수정을 위해 comment form에 initial로 comment를 넣어줌
            form = CommentForm(request.POST or None, initial=initial_dict)
            self.object = self.get_object()
            # context에 comment를 넗은 comment_form을 넣고 return
            context = self.get_context_data(object=self.object)
            context["comment_edit_form"] = form
            context["comment_pk"] = comment.pk

            return self.render_to_response(context)
        else:
            # 수정이 아니라면 기본 object를 return
            self.object = self.get_object()
            context = self.get_context_data(object=self.object)

        return self.render_to_response(context)


# 글 좋아요 기능
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # 본인 글은 제외
    if request.user==post.author:
        messages.warning(request, "작성한 회원은 좋아요를 누를수 없습니다")
        return redirect('nboard:post_detail', pk=pk)
    post.like_user.add(request.user)
    messages.success(request, f"{post.author} 좋아요")
    # 요청한 링크로 redirect
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)


# 글 좋아요 취소 기능
def post_unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user.remove(request.user)
    messages.success(request, f"{post.author} 좋아요 취소")
    # 요청한 링크로 redirect
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)


# 댓글 삭제기능
# post_detail로 돌아가기 위한 post.pk와
# 삭제하기위한 comment.pk를 같이 받는다
def comment_delete(request, pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    return redirect('nboard:post_detail', pk=pk)


# 댓글 수정기능
# post_detail로 돌아가기 위한 post.pk와
# 수정하기위한 comment.pk를 같이 받는다
def comment_edit(request, pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    form = CommentForm(request.POST or None,
                       instance=comment)
    if request.method == 'POST':
        if form.is_valid():
            comment_form = form.save(commit=False)
            comment_form.comment = request.POST.get("comment")
            comment_form.save()

    return redirect('nboard:post_detail', pk=pk)


# CBV기반 as_view()
post_create = PostCreateView.as_view()
post_update = PostUpdateView.as_view()
post_list = PostListView.as_view()
post_delete = PostDeleteView.as_view()

nboard/templates/nboard/comment.html
{% load bootstrap4 %}
{% block content %}
<div class="container">
  {% if comment_list %}
  <div class="container">
    {% for comment in comment_list %}
    <div class="col">
      <div>작성자 :{{comment.author}}</div>
      <div>{{comment.comment}}</div>
      {% if request.user == comment.author %}
      <div class="container">
        <div class="">
          <form action="" method="get">
            <input type="hidden" value="{{ comment.pk }}" name="pk" />
            <input type="submit" value="수정" />
          </form>

          <a href="{% url 'nboard:comment_delete' post.pk comment.pk %}">삭제</a>
        </div>
      </div>
      {% endif %}
    </div>
    <hr />
    {% endfor %}
  </div>
  {% endif %}
</div>
<div class="container">
  {% if comment_edit_form %}
    {% include "nboard/form.html" with submit_label="코멘트 수정" %}
  {% else %}
    {% include "form.html" with submit_label="코멘트 저장" %}
  {% endif %}
</div>
{% endblock %}

nboard/templates/nboard/form.html
{% load bootstrap4 %} {% block content %}
<div class="container">
  <div class="row">
    <form
      method="post"
      action="{% url 'nboard:comment_edit' post.pk comment_pk %}"
      enctype="multipart/form-data"
    >
      {% csrf_token %} {% bootstrap_form comment_edit_form %}
      <button type="submit" class="btn btn-primary mt-2">
        {{ submit_label|default:"Submit" }}
      </button>
    </form>
  </div>
</div>
{% endblock %}

nboard/templates/nboard/post_delete.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    <div class="alert alert-danger" role="alert">
 정말 삭제하시겠습니까?
</div>
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">삭제하기</button>
</form>
{% endblock %}

nboard/templates/nboard/post_detail.html
{% extends "base.html" %}
{% load bootstrap4 nboard_tags humanize %}
{% block content %}
<div class="container-xxl">
    <div class="container">
        <div class="card text-center">
            {% if post.photo %}
            <img
                    src="{{ post.photo.url }}"
                    class="rounded mx-auto d-block"
                    alt="post_photo"
            />
            {% else %}
            <svg
                    class="bd-placeholder-img card-img-top"
                    width="100%"
                    height="225"
                    xmlns="http://www.w3.org/2000/svg"
                    role="img"
                    aria-label="Placeholder: Thumbnail"
                    preserveAspectRatio="xMidYMid slice"
                    focusable="false"
            >
                <title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c"></rect>
                <text x="50%" y="50%" fill="#eceeef" dy=".3em">이미지 없음</text>
            </svg>
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ post.author }}</h5>
                <p class="card-text">{{ post.message|linebreaks }}</p>
                <p class="card-text">
                <div>
                    {% for tag_name in post.tag.all %}
                        <span class="badge bg-primary">
                            #{{ tag_name }}
                        </span>
                    {% endfor %}
                </div>
                </p>
                <p class="card-text">
                    <small class="text-muted">{{ post.updated_at | naturaltime}}</small>
                </p>
            </div>
        </div>
        <div class="container mt-3 text-end">
            {% if post|is_like_user:user %}
            <i class="bi bi-heart-fill"></i>
            <a href="{% url 'nboard:post_unlike' post.pk %}" style="color: inherit">
                <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="16"
                        height="16"
                        fill="currentColor"
                        class="bi bi-heart-fill"
                        viewBox="0 0 16 16"
                >
                    <path
                            fill-rule="evenodd"
                            d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"
                    />
                </svg>
            </a>

            {% else %}
            <i class="bi bi-heart"></i>
            <a href="{% url 'nboard:post_like' post.pk %}" style="color: inherit">
                <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="16"
                        height="16"
                        fill="currentColor"
                        class="bi bi-heart"
                        viewBox="0 0 16 16"
                >
                    <path
                            d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"
                    />
                </svg>
            </a>
            {% endif %}
            {% if request.user == post.author %}
              <a href="{% url 'nboard:post_update' post.id %}" class="btn btn-primary">포스팅 수정</a>
              <a href="{% url 'nboard:post_delete' post.id %}" class="btn btn-primary">포스팅 삭제</a>
            {% endif %}
        </div>
    </div>
    <hr/>
    <div class="container">
        <div class="container">댓글</div>
        {% include 'nboard/comment.html' %}
    </div>
</div>

{% endblock %}

nboard/templates/nboard/post_form.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
    {% include "form.html" with submit_label="포스트 저장" %}
{% endblock %}

nboard/templates/nboard/post_list.html
{% load bootstrap4 humanize %}
{% if post_list %}
{% for post in post_list %}
<div class="col bd-highlight">
  <div class="card shadow-sm h-100">
    {% if post.photo %}
    <img
      src="{{ post.photo.url }}"
      class="bd-placeholder-img card-img-top mx-auto d-block"
      style="width=100%; height: 100%"
    />
    {% else %}
    <svg
      class="bd-placeholder-img card-img-top"
      width="100%"
      height="100%"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-label="Placeholder: Thumbnail"
      preserveAspectRatio="xMidYMid slice"
      focusable="false"
    >
      <title>Placeholder</title>
      <rect width="100%" height="100%" fill="#55595c"></rect>
      <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#eceeef" dy=".3em">이미지 없음</text>
    </svg>
    {% endif %}

    <div class="card-body">
      <h5 class="card-title">{{ post.author }}</h5>
      <p class="card-text">
        {% for tag_name in post.tag.all %}
        <span class="badge bg-primary">
            #{{ tag_name }}
        </span>
        {% endfor %}
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button
            type="button"
            class="btn btn-sm btn-outline-secondary"
            onclick="location.href='{% url 'nboard:post_detail' post.id %}'"
          >
            View
          </button>
        </div>
        <small class="text-muted">{{ post.updated_at | naturaltime }}</small>
      </div>
    </div>
  </div>
</div>

{% endfor %} {% endif %}

nboard/templates/nboard/post_update.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
{% include "form.html" with submit_label="포스트 수정" %}
{% buttons %}
{% endbuttons %}
{% endblock %}